# Generated by Django 4.2.4 on 2023-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
