# Generated by Django 4.2.4 on 2023-09-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0002_user_confirm_password_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
