# Generated by Django 4.2.4 on 2023-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0003_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile-images'),
        ),
    ]
