# Generated by Django 4.2.4 on 2023-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0005_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_enrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
