# Generated by Django 4.2.4 on 2023-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0007_user_upload_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload_resume',
            field=models.FileField(blank=True, null=True, upload_to='uploaded-resume'),
        ),
    ]
