# Generated by Django 4.2.4 on 2023-09-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0013_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
