# Generated by Django 4.2.4 on 2023-09-18 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0018_userselectedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSelectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_jobs', to='training_placement.job')),
                ('user', models.ManyToManyField(related_name='selected_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSelectedJob',
        ),
    ]
