# Generated by Django 4.2.4 on 2023-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_placement', '0020_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
